### ISSUE TITLE
Bug it_world_crawler (None.text)

### ISSUE THREAD

**Issue by egorgorban** [unit-team-spbu/backend#23]
**Описание бага**

> it world где-то наругался мол не может text от None взять, хз где

**Ожидаемое поведение**
Ошибок подобного рода возникать не должно

**Возможное решение**
Везде где можно, сделаю проверку на None, чтобы ни у каких объектов, тип которых может быть None, не вызывались методы text и get('_smth_')

**Comment by katunilya** [comment]
Смотри, трейс ошибки:

```
error handling worker <WorkerContext [it_world_crawler.get_upcoming_events_http] at 0x7f764a2e37f0>: 'NoneType' object has no attribute 'text'
Traceback (most recent call last):
  File "/mnt/d/dev/unit-team-spbu/backend/das/event_das/.venv/lib/python3.8/site-packages/nameko/containers.py", line 392, in _run_worker
    result = method(*worker_ctx.args, **worker_ctx.kwargs)
  File "./it_world_crawler.py", line 117, in get_upcoming_events_http
    events = self.get_events()
  File "./it_world_crawler.py", line 58, in get_events
    soup1.find('div', {'class': 'detail'}).text.split(
AttributeError: 'NoneType' object has no attribute 'text'
```

видимо не на всех страницах есть `<div class="detail">`
