### ISSUE TITLE
Ошибка при добавлении в event_das

### ISSUE THREAD

**Issue by MaxKuznets0v** [unit-team-spbu/backend#50]
## Опишите ошибку
Во время сохранения новых событий в `event_das` в методе `eta.analyze_events` происходит ошибка:
```
Traceback (most recent call last):
   File "/usr/local/lib/python3.9/site-packages/nameko/containers.py", line 392, in _run_worker
     result = method(*worker_ctx.args, **worker_ctx.kwargs)
   File "./event_theme_analyzer.py", line 93, in analyze_events
     event["tags"].extend(self._analyze(event["description"]))
   File "./event_theme_analyzer.py", line 66, in _analyze
     mean = statistics.mean([tags[key] for key in tags.keys()])
   File "/usr/local/lib/python3.9/statistics.py", line 315, in mean
     raise StatisticsError('mean requires at least one data point')
 statistics.StatisticsError: mean requires at least one data point
```
Видимо, словарь tags по какой-то причине оказывается пустым.
## Шаги для воспроизведения
Был сделан запрос в `rec`:
```
GET http://localhost:8001/events HTTP/1.1
```
При этом в методе `update` в `rec` были закомментированы строки:
```
try:
     # get_res.append(self.it_events_rpc.get_upcoming_events.call_async())
     get_res.append(self.softline_rpc.get_upcoming_events.call_async())
     # get_res.append(self.it_world_rpc.get_upcoming_events.call_async())
except:
     pass
```
То есть, события собирались только с `softline_crawler`.
## Ожидаемое поведение
Такие ошибки не должны возникать, и события должны сохраняться в `event_das`.

**Comment by katunilya** [comment]
Проблема возникает, когда `eta` не находит тэги из описания. Ждите хотфикс
